import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { analysisApi } from '../api/analysisApi';
import DragDropUploader from '../components/upload/DragDropUploader';
import { 
  FileText, 
  Upload, 
  Layers, 
  ChevronRight, 
  ShieldAlert, 
  AlertCircle,
  Clock,
  CheckCircle2,
  Users
} from 'lucide-react';

const UploadCasePage = () => {
  const navigate = useNavigate();
  const [isProcessing, setIsProcessing] = useState(false);
  const [error, setError] = useState(null);
  const [narrativeText, setNarrativeText] = useState('');

  // Pipeline status steps
  const [ocrSteps, setOcrSteps] = useState([
    { label: 'Ingesting patient document findings', status: 'pending' },
    { label: 'Running entity mapping & drug validation', status: 'pending' },
    { label: 'Retrieving openFDA Database Signal metrics', status: 'pending' },
    { label: 'Querying Milvus KB for clinical guidelines', status: 'pending' },
    { label: 'Generating safety assessment & evidence summaries', status: 'pending' }
  ]);

  // Segmented multi-cases results state
  const [segmentedResult, setSegmentedResult] = useState(null);

  const updateStepStatus = (index, status) => {
    setOcrSteps(prev => prev.map((step, idx) => {
      if (idx === index) return { ...step, status };
      return step;
    }));
  };

  const executePipeline = async (uploadPromise) => {
    setIsProcessing(true);
    setError(null);
    setSegmentedResult(null);
    
    // Reset steps
    setOcrSteps([
      { label: 'Ingesting patient document findings', status: 'active' },
      { label: 'Running entity mapping & drug validation', status: 'pending' },
      { label: 'Retrieving openFDA Database Signal metrics', status: 'pending' },
      { label: 'Querying Milvus KB for clinical guidelines', status: 'pending' },
      { label: 'Generating safety assessment & evidence summaries', status: 'pending' }
    ]);

    try {
      // 1. Run file/text Ingestion POST /analyze/
      const ingestData = await uploadPromise;
      updateStepStatus(0, 'completed');
      updateStepStatus(1, 'active');

      const analysisId = ingestData.analysis_id || ingestData.report_id;
      if (!analysisId) {
        throw new Error('Analysis ID was not generated by backend.');
      }

      // Simulated delays for clinical visualization feedback
      await new Promise(resolve => setTimeout(resolve, 800));
      updateStepStatus(1, 'completed');
      updateStepStatus(2, 'active');

      await new Promise(resolve => setTimeout(resolve, 1000));
      updateStepStatus(2, 'completed');
      updateStepStatus(3, 'active');

      // 2. Trigger analysis report compilation
      const reportData = await analysisApi.generateReport(analysisId);
      
      updateStepStatus(3, 'completed');
      updateStepStatus(4, 'active');

      await new Promise(resolve => setTimeout(resolve, 600));
      updateStepStatus(4, 'completed');

      // Wait a bit to show pipeline completion
      await new Promise(resolve => setTimeout(resolve, 500));

      if (reportData.total_cases_detected && reportData.total_cases_detected > 1) {
        // Multi-patient case segmented results
        setSegmentedResult(reportData);
        setIsProcessing(false);
      } else {
        // Single patient case - route directly to workspace
        navigate(`/workspace/${analysisId}`);
      }
    } catch (err) {
      console.error('Pipeline failed:', err);
      setError(err.response?.data?.detail || err.message || 'An error occurred during case safety ingestion.');
      setIsProcessing(false);
    }
  };

  const handleFileUpload = (file) => {
    executePipeline(analysisApi.analyze(file, null));
  };

  const handleTextSubmit = (e) => {
    e.preventDefault();
    if (!narrativeText.trim()) return;
    executePipeline(analysisApi.analyze(null, narrativeText.trim()));
  };

  return (
    <div className="space-y-8 animate-fadeIn max-w-4xl mx-auto">
      <div>
        <h1 className="text-2xl font-black text-slate-800 dark:text-white tracking-tight">
          Case Ingestion & Ingest
        </h1>
        <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 font-medium">
          Upload medical report images, digital documents, or paste patient narratives to trigger pharmacovigilance reports.
        </p>
      </div>

      {error && (
        <div className="p-4 bg-red-50 dark:bg-red-950/20 border border-red-200 dark:border-red-900/50 rounded-xl text-xs font-semibold text-red-650 dark:text-red-400 flex items-center gap-3">
          <AlertCircle className="h-5 w-5 flex-shrink-0" />
          <span>{error}</span>
        </div>
      )}

      {!segmentedResult ? (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* File Upload zone (2/3 width) */}
          <div className="md:col-span-2 space-y-6">
            <DragDropUploader 
              onUploadSuccess={handleFileUpload}
              isProcessing={isProcessing}
              ocrSteps={ocrSteps}
            />
          </div>

          {/* Paste Area (1/3 width) */}
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl shadow-sm p-6 space-y-4 flex flex-col">
            <h3 className="text-xs font-bold text-slate-800 dark:text-white uppercase tracking-wider flex items-center gap-2">
              <FileText className="h-4 w-4 text-brand-500" />
              <span>Paste Clinical Narrative</span>
            </h3>
            
            <form onSubmit={handleTextSubmit} className="flex-1 flex flex-col space-y-4">
              <textarea
                value={narrativeText}
                onChange={(e) => setNarrativeText(e.target.value)}
                placeholder="Patient is a 52yo female with history of rheumatoid arthritis who was started on Methotrexate 15mg weekly. After 6 weeks, she presented with elevated AST/ALT levels..."
                disabled={isProcessing}
                className="flex-1 w-full min-h-[160px] p-3 bg-slate-50 dark:bg-slate-850 border border-slate-250 dark:border-slate-755 rounded-xl text-xs font-semibold placeholder-slate-400 focus:outline-none focus:border-brand-500 text-slate-800 dark:text-slate-200 resize-none"
              />
              
              <button
                type="submit"
                disabled={isProcessing || !narrativeText.trim()}
                className="w-full py-2.5 bg-brand-600 hover:bg-brand-700 disabled:bg-slate-200 dark:disabled:bg-slate-800 text-white rounded-lg text-xs font-bold transition-all cursor-pointer shadow-md shadow-brand-600/15 flex items-center justify-center gap-1.5"
              >
                <span>Analyze Narrative</span>
                <ChevronRight className="h-4 w-4" />
              </button>
            </form>
          </div>
        </div>
      ) : (
        /* Segmented Case deck (For multi-patient documents) */
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-6 rounded-xl shadow-sm space-y-6 animate-fadeIn">
          <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-4">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-brand-50 dark:bg-brand-950/40 rounded-lg text-brand-500">
                <Users className="h-6 w-6" />
              </div>
              <div>
                <h3 className="text-sm font-bold text-slate-800 dark:text-white uppercase tracking-wider">
                  Segmented Multi-Patient Case Records
                </h3>
                <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                  Detected {segmentedResult.total_cases_detected} patient cases inside your ingested clinical summary.
                </p>
              </div>
            </div>
            
            <div className="flex items-center gap-2 px-3 py-1 bg-brand-50 dark:bg-brand-950/40 border border-brand-100 dark:border-brand-900 rounded-lg">
              <Layers className="h-4 w-4 text-brand-600 dark:text-brand-400" />
              <span className="text-xs font-bold text-brand-700 dark:text-brand-400">
                Segmented Bundle
              </span>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {segmentedResult.cases.map((caseItem, idx) => (
              <div 
                key={caseItem.case_id || idx} 
                className="bg-slate-50 dark:bg-slate-850/50 border border-slate-200/60 dark:border-slate-800 p-5 rounded-xl hover-scale flex flex-col justify-between"
              >
                <div className="space-y-3">
                  <div className="flex justify-between items-start">
                    <span className="text-[10px] font-black text-brand-600 dark:text-brand-400 uppercase tracking-widest bg-brand-50 dark:bg-brand-950/40 px-2 py-0.5 rounded">
                      Case {idx + 1}
                    </span>
                    <span className="text-[10px] text-slate-400 font-bold">
                      ID: {caseItem.case_id || 'PV-TEMP'}
                    </span>
                  </div>

                  <div className="space-y-1.5 text-xs text-slate-650 dark:text-slate-300">
                    <p className="font-semibold">
                      <span className="text-slate-400 block text-[9px] uppercase font-bold tracking-wider">Primary Suspect Drug</span>
                      <span className="text-slate-800 dark:text-slate-100 font-black">
                        {caseItem.drug_information?.product_active_ingredient || 'Unknown Ingredient'}
                      </span>
                    </p>
                    <p className="font-semibold mt-2">
                      <span className="text-slate-400 block text-[9px] uppercase font-bold tracking-wider">Patient Details</span>
                      <span>
                        Age Group: {caseItem.patient_details?.age_group?.meaning || 'Adult'}, Weight: {caseItem.patient_details?.patient_weight ? `${caseItem.patient_details.patient_weight} kg` : 'Not Specified'}
                      </span>
                    </p>
                    <p className="font-semibold text-slate-500 dark:text-slate-400 mt-2 leading-relaxed italic line-clamp-3">
                      {caseItem.summary || 'No narrative description provided.'}
                    </p>
                  </div>
                </div>

                <button
                  onClick={() => {
                    const childId = caseItem.analysis_id || (caseItem.report_file || '').match(/\/report\/download\/(.+)\?/)?.[1];
                    if (childId) {
                      navigate(`/workspace/${childId}`);
                    } else {
                      alert('Could not resolve case workspace identifier.');
                    }
                  }}
                  className="w-full flex items-center justify-center gap-1.5 py-2.5 mt-5 border border-brand-200 dark:border-brand-800 hover:border-brand-500 dark:hover:border-brand-500 hover:bg-brand-50 dark:hover:bg-brand-950/20 text-brand-600 dark:text-brand-400 font-bold text-[11px] rounded-lg transition-all cursor-pointer"
                >
                  <span>Open Case Workspace</span>
                  <ChevronRight className="h-4 w-4" />
                </button>
              </div>
            ))}
          </div>

          <div className="flex justify-end pt-4 border-t border-slate-105 dark:border-slate-800">
            <button
              onClick={() => {
                setSegmentedResult(null);
                setNarrativeText('');
              }}
              className="px-4 py-2 border border-slate-200 dark:border-slate-800 hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-300 rounded-lg text-xs font-bold transition-all cursor-pointer"
            >
              Upload Another Report
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default UploadCasePage;
